# theme: jekyll-theme-cayman
# theme: jekyll-theme-minima
theme: jekyll-theme-modernist

title: Paul Landers at pwxn.xyz
email: pwxn@pwxn.xyz
description: A site for my hobbies and development projects
baseurl: ""
url: "pwxn.xyz"
github_username: pwxn
show_downloads: false

markdown: kramdown

repository: pwxn/pwxnxyz

plugins:
  - jekyll-feed
