theme: jekyll-theme-minimal

title: Paul Landers
email: paul@thelanders.family
description: Paul Landers' hobbies and software
baseurl: ""
url: "https://p3l6.dev"
logo: /assets/images/logos/main.svg
github_username: p3l6
show_downloads: false

markdown: kramdown

repository: p3l6/blog

plugins:
  - jekyll-feed
  - jekyll-redirect-from

timezone: America/New_York

permalink: pretty
