# theme: jekyll-theme-cayman
# theme: jekyll-theme-minima
theme: jekyll-theme-modernist

title: Paul Landers at pwxn.dev
email: pwxn@pwxn.dev
description: Paul Landers' hobbies and software development
baseurl: ""
url: "pwxn.dev"
github_username: pwxn
show_downloads: false

markdown: kramdown

repository: pwxn/pwxndev

plugins:
  - jekyll-feed
  - jekyll-redirect-from

timezone: America/Denver

permalink: pretty
