# theme: jekyll-theme-cayman
# theme: jekyll-theme-minima
theme: jekyll-theme-modernist

title: Paul Landers at pwxn.xyz
email: pwxn@pwxn.xyz
description: About me and my personal development projects
baseurl: ""
url: ""
github_username: pwxn
show_downloads: false

markdown: kramdown

repository: pwxn/pwxnxyz
