# theme: jekyll-theme-cayman
# theme: jekyll-theme-minima
theme: jekyll-theme-modernist

title: Paul Landers at pwxn.dev
email: pwxn@pwxn.dev
description: A site for my hobbies and development projects
baseurl: ""
url: "pwxn.dev"
github_username: pwxn
show_downloads: false

markdown: kramdown

repository: pwxn/pwxndev

plugins:
  - jekyll-feed

timezone: America/Denver

permalink: pretty
