theme: jekyll-theme-minimal

title: Paul Landers
email: pwxn@pwxn.dev
description: Paul Landers' hobbies and software development
baseurl: ""
url: "https://pwxn.dev"
logo: /assets/images/logos/main.svg
github_username: pwxn
show_downloads: false

markdown: kramdown

repository: pwxn/pwxndev

plugins:
  - jekyll-feed
  - jekyll-redirect-from

timezone: America/Denver

permalink: pretty
